### ISSUE TITLE
CI refactor

### ISSUE THREAD

**Issue by Wulf** [Wulf/dsync#76]
Can the `cargo test` step run after `cargo build`? I'm assume it can reuse the cached/compiled artifacts so it can potentially run faster

![image](https://github.com/Wulf/dsync/assets/4259838/ab61faad-c440-4eb1-80bd-3cad1282a92b)

**Comment by Wulf** [comment]
Going to close this, it's not a big deal

**Comment by hasezoey** [comment]
from my testing because `cargo test` uses a different target than `cargo build` (which uses `debug` by default, and test is `test`), it only re-uses the downloaded crates at most, but not any(or at least much) build artifacts, and from what i could find it is currently just faster for this package to run it side-by-side
