### ISSUE TITLE
feat: `--async` option for compiled binary (CLI)

### ISSUE THREAD

**Issue by jjangga0214** [Wulf/dsync#96]
Hi!

When using compiled binary (by `cargo install dsync`, not `cargo add dsync`), `--async` option is not there.
I hope it's to be supported.

What do you think?

**Comment by hasezoey** [comment]
> When using compiled binary (by cargo install dsync, not cargo add dsync), --async option is not there.

you need to compile it with the feature enabled, `async` is not a default feature

use `cargo install dsync --features async`

**Comment by jjangga0214** [comment]
Yes, but that does not mean it will create async code, in my experience.
And the freedom to choose on Runtime is still good.

**Comment by hasezoey** [comment]
i dont quite understand what this issue is about, so some general information:

for async code to be generated, you need to:
- enable feature `async` at compile time
- enable via flag `--async` at runtime

https://github.com/Wulf/dsync/blob/007ace83c139f67e1d85ed4829cf0b6953d121df/src/bin/main.rs#L57-L60

**Comment by jjangga0214** [comment]
Oh, I checked `--help` but missed reading `--async`.
Probably I thought I did `cargo install dsync --features async` but actually `cargo install dsync`.
Thanks for the clarification!
